**Customers Data**

In [11]:
import pandas as pd

customers = pd.read_csv('../data/raw/customers.csv')
customers.head()

,customer_id,name,email,gender,city,country,signup_date,age,tier
0,C00000,Randy Rosales,shawnmiller@example.net,other,Robertsside,GB,2025-08-16,55,silver
1,C00001,Bonnie Hansen,louis31@example.net,male,East Lisaborough,CA,2024-02-23,22,bronze
2,C00002,Calvin Rios,ashley26@example.com,male,Port Danielle,DE,2023-02-20,32,gold
3,C00003,Jonathan Marquez,nicholasmiller@example.org,other,Janethaven,IN,2025-06-12,42,bronze
4,C00004,Gary Hill,brenthayes@example.org,female,Velasquezmouth,GB,2022-04-08,42,gold

In [16]:
customers.shape

(3000, 9)

In [21]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  3000 non-null   str
 1   name         3000 non-null   str
 2   email        3000 non-null   str
 3   gender       3000 non-null   str
 4   city         3000 non-null   str
 5   country      3000 non-null   str
 6   signup_date  3000 non-null   str
 7   age          3000 non-null   int64
 8   tier         3000 non-null   str
dtypes: int64(1), str(8)
memory usage: 434.6 KB

In [27]:
customers.isna().sum()

customer_id    0
name           0
email          0
gender         0
city           0
country        0
signup_date    0
age            0
tier           0
dtype: int64

In [32]:
customers['tier'].value_counts()

tier
platinum    780
silver      747
bronze      744
gold        729
Name: count, dtype: int64

**Orders data**

In [12]:
orders = pd.read_csv('../data/raw/orders.csv')
orders.head()

,order_id,customer_id,order_date,status,channel,discount_pct,shipping_country
0,ORD000000,C01187,2023-06-29,completed,mobile,0.09,US
1,ORD000001,C01029,2022-11-03,refunded,store,0.10,GB
2,ORD000002,C01599,2022-08-12,pending,store,0.30,DE
3,ORD000003,C02880,2023-08-04,cancelled,web,0.34,DE
4,ORD000004,C01465,2022-06-28,refunded,mobile,0.07,GB

In [17]:
orders.shape

(8000, 7)

In [22]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          8000 non-null   str
 1   customer_id       8000 non-null   str
 2   order_date        8000 non-null   str
 3   status            8000 non-null   str
 4   channel           8000 non-null   str
 5   discount_pct      8000 non-null   float64
 6   shipping_country  8000 non-null   str
dtypes: float64(1), str(6)
memory usage: 749.5 KB

In [28]:
orders.isna().sum()

order_id            0
customer_id         0
order_date          0
status              0
channel             0
discount_pct        0
shipping_country    0
dtype: int64

**Products Data**

In [13]:
products = pd.read_csv('../data/raw/products.csv')
products.head()

,product_id,name,category,sub_category,price,cost,stock_qty,is_active
0,P0000,Multi-layered 6thgeneration analyzer,Beauty,Group,171.98,146.15,89,False
1,P0001,Reduced full-range customer loyalty,Clothing,Around,391.79,10.09,86,False
2,P0002,Enterprise-wide didactic Graphic Interface,Beauty,Participant,349.15,73.90,516,False
3,P0003,Advanced bifurcated support,Home & Kitchen,May,146.95,106.32,71,False
4,P0004,Upgradable clear-thinking capability,Electronics,Trade,82.16,57.27,227,False

In [18]:
products.shape

(300, 8)

In [24]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    str
 1   name          300 non-null    str
 2   category      300 non-null    str
 3   sub_category  299 non-null    str
 4   price         300 non-null    float64
 5   cost          300 non-null    float64
 6   stock_qty     300 non-null    int64
 7   is_active     300 non-null    bool
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 31.8 KB

In [29]:
products.isna().sum()

product_id      0
name            0
category        0
sub_category    1
price           0
cost            0
stock_qty       0
is_active       0
dtype: int64

**Order Items Data**

In [14]:
order_items = pd.read_csv('../data/raw/order_items.csv')
order_items.head()

      item_id   order_id product_id  quantity  unit_price  returned
0  ITEM000000  ORD000000      P0288         7      114.43      True
1  ITEM000001  ORD000000      P0010         2      297.42     False
2  ITEM000002  ORD000000      P0269         4      127.14     False
3  ITEM000003  ORD000001      P0031         5       56.48     False
4  ITEM000004  ORD000002      P0044         4      316.66      True

In [19]:
order_items.shape

(23942, 6)

In [25]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 23942 entries, 0 to 23941
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     23942 non-null  str
 1   order_id    23942 non-null  str
 2   product_id  23942 non-null  str
 3   quantity    23942 non-null  int64
 4   unit_price  23942 non-null  float64
 5   returned    23942 non-null  bool
dtypes: bool(1), float64(1), int64(1), str(3)
memory usage: 1.5 MB

In [30]:
order_items.isna().sum()

item_id       0
order_id      0
product_id    0
quantity      0
unit_price    0
returned      0
dtype: int64

**Events Data**

In [15]:
events = pd.read_csv('../data/raw/events.csv')
events.head()

,event_id,session_id,customer_id,event_type,product_id,timestamp,device
0,E0000000,c22c0a94-5115-44ab-a29e-802eab74234e,C00322,page_view,P0089,2024-09-25 16:12:29,mobile
1,E0000001,b8e68ef4-2764-4f60-9cce-9f811fb78f55,C00229,search,P0171,2022-09-11 14:23:12,desktop
2,E0000002,46be6b8e-cbce-468a-ab4b-8d3545c0dcb4,C02132,product_view,NaN,2022-07-01 11:36:22,desktop
3,E0000003,39172a77-608b-4496-b91a-028a538ded75,C00791,checkout_start,P0231,2023-05-18 13:23:13,desktop
4,E0000004,452abe9a-a49e-4aff-a483-365efab291df,C00442,purchase,NaN,2022-12-17 19:47:50,mobile

In [20]:
events.shape

(50000, 7)

In [26]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event_id     50000 non-null  str
 1   session_id   50000 non-null  str
 2   customer_id  42769 non-null  str
 3   event_type   50000 non-null  str
 4   product_id   30023 non-null  str
 5   timestamp    50000 non-null  str
 6   device       50000 non-null  str
dtypes: str(7)
memory usage: 6.9 MB

In [31]:
events.isna().sum()

event_id           0
session_id         0
customer_id     7231
event_type         0
product_id     19977
timestamp          0
device             0
dtype: int64